### ISSUE TITLE
No possibility to add timezone in the URL

### ISSUE THREAD

**Issue by roadburns** [open-meteo-ruby/open-meteo-ruby#69]
Hi there, first of all thanks for this very nice tool.
I've been struggling to get the results for my timezone which is quite relevant in my case (an not only I guess). I realized that it would be enough to make the tool capable to append the specific TZ at the end of the URL to avoid crazy results conversion.

So basically this is what I've done:
on file: open_meteo/entities/contracts/location_contract.rb
I've added added
	required(:timezone).filled(:string)
	rule(:timezone) { key.failure("must be in the extended form: Europe/Rome") unless value.is_a?(String) }

and on file: open_meteo/entities/location.rb
I've added
	attribute :timezone, OpenMeteo::Types::String
	{ latitude:, longitude:, timezone: }

In this way I can have a timezone specified in the code:
location = OpenMeteo::Entities::Location.new(latitude: xx.yy, longitude: xx.yy.to_d, timezone: 'Europe/Rome')

and I'll have the proper results thanks to the "&timezone=Europe/Rome" appended to the URL.
I'm sure this is not the most elegant way, I'm not a developer, however it resolved my problem. So unless there's a built-in way to achieve the same with the current code which I've missed, such functionality would be very nice to have.

Thanks again and have a good day.

**Comment by peterfication** [comment]
Sorry for the late response. Thanks a lot for your request. I think it makes sense to add this.

I will see if I have the time for it the next couple of days.

**Comment by martinezcoder** [comment]
@roadburns thanks for your contribution! your proposal will be released in the new version of the gem.
